---
abstract: 'a smaller Lingua::Boolean, with support for more languages'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Lingua::Boolean::Tiny
name: Lingua-Boolean-Tiny
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.6.2
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Lingua-Boolean-Tiny
  homepage: https://metacpan.org/release/Lingua-Boolean-Tiny
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-lingua-boolean-tiny
version: 0.004
